# Generated by Django 4.1.7 on 2023-03-29 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(blank=True, max_length=250, null=True, verbose_name='نظرات')),
                ('isActive', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('send_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات ')),
                ('image', models.FileField(blank=True, null=True, upload_to='Media/article', verbose_name='Image')),
                ('date_release', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('tag', models.TextField(blank=True, max_length=250, null=True, verbose_name='تگ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog1.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
